(()=>{
const q=s=>document.querySelector(s),frame=q('#site'),S={el:null,type:null,candidate:null};
const base=()=>window.CSUM_CONFIG.imageApiBase;
function token(){let t=sessionStorage.getItem('csum_image_admin_token_v4');if(!t){t=prompt('Admin token')||'';if(t)sessionStorage.setItem('csum_image_admin_token_v4',t)}return t}
function headers(){return {'content-type':'application/json','x-csum-admin-token':token()}}
function setStatus(x){q('#status').textContent=x}
function selector(el){const parts=[];while(el&&el.nodeType===1&&el!==frame.contentDocument.body){if(el.id){parts.unshift('#'+CSS.escape(el.id));break}const tag=el.tagName.toLowerCase();const sib=[...el.parentElement.children].filter(x=>x.tagName===el.tagName);parts.unshift(tag+(sib.length>1?':nth-of-type('+(sib.indexOf(el)+1)+')':''));el=el.parentElement}return parts.join(' > ')}
function select(el){S.el=el;S.type=el.tagName==='IMG'?'image':'text';q('#empty').hidden=true;q('#editor').hidden=false;q('#type').value=S.type==='image'?'Фотография':'Текст';q('#id').value=S.type==='text'?selector(el):(el.dataset.aiKey||el.dataset.aiSrc||el.id||'editor-image');q('#imageTools').hidden=S.type!=='image';q('#textTools').hidden=S.type!=='text';q('#value').value=S.type==='image'?'Ассоциативная журнальная фотография по теме этого блока. Без генерируемых логотипов, вывесок и читаемого текста. BRAND LOCK: логотип допускается только отдельным оригинальным asset без изменения.':el.textContent.trim();frame.contentDocument.querySelectorAll('.csum-admin-selected').forEach(x=>x.classList.remove('csum-admin-selected'));el.classList.add('csum-admin-selected')}
frame.onload=()=>{const d=frame.contentDocument,style=d.createElement('style');style.textContent='.csum-admin-selected{outline:3px solid #1769ff!important;outline-offset:3px;cursor:pointer!important} body *{cursor:default} img,h1,h2,h3,p,span,a{cursor:pointer!important}';d.head.append(style);d.addEventListener('click',e=>{const el=e.target.closest('img,h1,h2,h3,p,span');if(!el)return;e.preventDefault();e.stopPropagation();select(el)},true)};
q('#previewText').onclick=async()=>{if(!S.el)return;const text=q('#value').value,sel=q('#id').value;S.el.textContent=text;setStatus('Сохраняю черновик…');try{const r=await fetch(base()+'/api/editor/draft',{method:'POST',headers:headers(),body:JSON.stringify({selector:sel,text})}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);setStatus('Черновик сохранён. На production ещё не опубликован.')}catch(e){setStatus('Ошибка: '+e.message)}};
q('#regenerate').onclick=async()=>{if(!S.el)return;setStatus('Генерация…');try{const r=await fetch(base()+'/api/generate',{method:'POST',headers:headers(),body:JSON.stringify({id:q('#id').value||'editor-image',prompt:q('#value').value,model:q('#model').value,aspect_ratio:'16:9',output_format:'webp'})}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);S.candidate=d;q('#candidate').src=d.url;q('#candidate').style.display='block';S.el.src=d.url;setStatus('Кандидат PENDING. Стоимость: '+(d.usage?.cost!=null?'$'+d.usage.cost:'не передана')+'.')}catch(e){setStatus('Ошибка: '+e.message)}};
q('#reject').onclick=async()=>{if(S.candidate?.candidate_key){try{await fetch(base()+'/api/reject',{method:'POST',headers:headers(),body:JSON.stringify({candidate_key:S.candidate.candidate_key,reasons:['Отклонено главным редактором']})})}catch{}}S.candidate=null;q('#candidate').style.display='none';frame.contentWindow.location.reload();setStatus('Кандидат отклонён и зафиксирован как REJECTED.')};
q('#approve').onclick=async()=>{if(!S.candidate?.candidate_key)return setStatus('Сначала создайте кандидат.');try{let r=await fetch(base()+'/api/approve',{method:'POST',headers:headers(),body:JSON.stringify({candidate_key:S.candidate.candidate_key})}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);r=await fetch(base()+'/api/apply',{method:'POST',headers:headers(),body:JSON.stringify({id:q('#id').value,candidate_key:S.candidate.candidate_key,prompt:S.candidate.prompt,model:S.candidate.model})});d=await r.json();if(!r.ok)throw Error(d.error||r.status);setStatus('Фото APPROVED и опубликовано.')}catch(e){setStatus('Ошибка: '+e.message)}};
q('#publish').onclick=async()=>{setStatus('Публикую текстовый Draft…');try{const r=await fetch(base()+'/api/editor/publish',{method:'POST',headers:headers(),body:'{}'}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);q('#state').textContent='Опубликовано v'+d.version;setStatus('Текст опубликован. Версия '+d.version+'.')}catch(e){setStatus('Ошибка: '+e.message)}};
})();